changed Environment and way to earn Connection #12
gshumilin/learning-server pull request #22
Opened 2022-09-29 14:14 UTC by gshumilin

2022-10-04 13:39 UTC, pavelzarubin requested changes

2022-10-04 13:39 UTC, pavelzarubin commented on src/Endpoints/CreateCategory.hs
> +  conn <- askConnection
У тебя постоянно из ```Enviroment``` достается ```Connection```. Давай это перенесем. Скажем сделаем методы для обработки запросов так, чтобы внутри них мы получали ```Connection```. Например сделаем  что-то типа, execQueryWithPool.

2022-10-06 14:45 UTC, pavelzarubin requested changes

2022-10-06 14:45 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
Смотри. У тебя Environment, как я вижу, должен являться частью бизнес логики, а не той части, от которой зависит с какой базой и как мы взаимодействием. Поэтому в нем не должно быть информации о соединении, вообще никакой. Потому что, если мы вдруг перейдем с одной базы на другую (например перейдем на MySql), то возможно там тип Connection будет совсем другой. Поэтому нам нужно сделать так, чтобы только часть взаимодействия с базой знала про Connection.

2022-10-06 14:47 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
Вообще это нужно выделить в отдельное ишью.

2022-10-07 08:24 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Я не задумывал Environment, как сущность, связанную только с бизнес-логикой. Если потребуется перейти на другую СУБД, то можно просто изменить Environment. Разве нет? Ведь мои функции не используют Connection, и хэндлер написан в полиморфной монаде.

2022-10-07 08:35 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
Да, но суть в том, что не нужно создавать сущности, которые одновременно связаны и с бизнес логикой и с частью связанной с базой. Идея как раз в том, чтобы описать всю бизнес логику отдельно. И когда у тебя будет смена базы, то тебе придется изменять только функции, связанные с обращением к базе. А у тебя получается, что эндпоинты не являются в полной мере частью бизнес логики, так как Enviroment к ней полностью не относится. К тому же, если ты выделишь полностью бизнесовую часть, то сможешь протестировать не только, ту часть где происходит якобы взаимодействие с базой, а весь роутинг, то есть всю логику работы сервера, а не только конкретные части.

2022-10-07 08:43 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Действительно, раз я могу тестировать только то, что в хэндле, то сейчас я могу протестировать только взаимодействие с базой. Как-то о тестировании роутинга я не думал. Получается, что мне как бы нужен хэндлер для всей логики, включающий в себя, например, хэндлер для роутинга и хендлеры для работы с каждым эндпоинтом.

2022-10-07 08:44 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Стоп, а как тогда всё-таки передать Connection конкретным функциям, работающим с базой. Таким функциям, например, как `query_` ?

2022-10-07 08:44 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
А вот подумай

2022-10-07 08:48 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
> Действительно, раз я могу тестировать только то, что в хэндле, то сейчас я могу протестировать только взаимодействие с базой. Как-то о тестировании роутинга я не думал. Получается, что мне как бы нужен хэндлер для всей логики, включающий в себя, например, хэндлер для роутинга и хендлеры для работы с каждым эндпоинтом.

тут как бы не просто тестирование роутинга, а имитация работы сервера. Ты сможешь тестировать конкретные эндпоинты, но обращание к ним будет, как будто сервер обрабатывает запрос.

2022-10-07 08:48 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Не, ну я так раньше делал, конечно. Писал выражения в стиле `let handle conn = Handle {fx = \q -> query_ conn q ...}. Но просто тогда придётся перед заполнением хэндлера создавать пул соединений, а это уже не бизнес-логика....

Есть ещё вариант, чтобы я создавал соединение прямо на уровне реализации функции fx, но это неэффективно. Это точно возможно решить вообще?

2022-10-07 08:53 UTC, pavelzarubin commented on src/Endpoints/CreateNews.hs
>          }
> Не, ну я так раньше делал, конечно. Писал выражения в стиле `let handle conn = Handle {fx = \q -> query_ conn q ...}`. Но просто тогда придётся перед заполнением хэндлера создавать пул соединений, а это уже не бизнес-логика....
Ну почему же. Подумай что является частью бизнес логики. Пул соединений создается в приложении один раз всего, и то до старта бизнесовой части.

2022-10-07 09:24 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Правильно ли я понял, что это можно сделать в main? То есть пусть main парсит конфиг, создаёт пул, заполняет хэндл и вызывает функцию работы сервера. Это корректно?

2022-10-07 09:44 UTC, gshumilin commented on src/Endpoints/CreateNews.hs
>          }
Смёрджу этот пр и создам новый. Всё-таки в рамках создания пула соединений, задача решена. А делать изменения структуры проекта в этой ветке как-то не к месту

2022-10-07 09:44 UTC, merged